name: "Release project"
inputs:
  repository:
    description: 'Repository to release'
    required: true
  source-branch:
    description: 'Source branch to release'
    required: true
  token:
    description: 'Token for repository access'
    required: true

runs:
  using: "composite"
  steps:
    - name: Install Python
      uses: actions/setup-python@v4.2.0
      with:
        python-version: '3.10'

    - name: Checkout git-repository-runner
      uses: actions/checkout@v3.0.2
      with: 
        token: ${{ inputs.token }}
        repository: gbtec-ag/git-repository-runner
        ref: refs/heads/feat/DES-2160
        path: git-repository-runner

    - name: Install dependencies
      run: |
        cd git-repository-runner
        pip install -r requirements.txt
      shell: bash

    - name: Run release workflow
      run: |
        mkdir "${GITHUB_WORKSPACE}/workdir"
        export REPO_HELPER_BASEDIR="${GITHUB_WORKSPACE}/workdir"
        export REPO_HELPER_SERVICES="${{ inputs.repository }}"
        cd "${GITHUB_WORKSPACE}/git-repository-runner"
        ./runner.py CreateRelease "${{ inputs.source-branch }}"
      shell: bash
