name: "Release project"
inputs:
  repository:
    description: 'Repository to release'
    required: true
  source-branch:
    description: 'Source branch to release'
    required: true
  runner-token:
    description: 'Token for repository git-repository-runner'
    required: true
  jira-user:
    description: 'User to access Jira API'
    required: true
  jira-token:
    description: 'Token to access Jira API'
    required: true
  slack-token:
    description: 'Token to access Slack API'
    required: true

runs:
  using: "composite"
  steps:
    - name: Install Python
      uses: actions/setup-python@v4.2.0
      with:
        python-version: '3.10'

    - name: Checkout git-repository-runner
      uses: actions/checkout@v3.0.2
      with: 
        token: ${{ inputs.runner-token }}
        repository: gbtec-ag/git-repository-runner
        ref: refs/heads/feat/DES-2160
        path: git-repository-runner

    - name: Install dependencies
      run: |
        cd git-repository-runner
        pip install -r requirements.txt
      shell: bash

    - name: Run release workflow
      run: |
        export REPO_HELPER_BASEDIR="${GITHUB_WORKSPACE}"
        export REPO_HELPER_SERVICES="${{ inputs.repository }}"
        export JIRA_USER="${{ inputs.jira-user }}"
        export JIRA_TOKEN="${{ inputs.jira-token }}"
        export SLACK_TOKEN="${{ inputs.slack-token }}"
        export TRIGGERING_USER="${{ github.triggering_actor }}"
        ./git-repository-runner/runner.py CreateRelease "${{ inputs.source-branch }}"
      shell: bash
