name: "Release project"
inputs:
  repository:
    description: 'Repository to release'
    required: true
  source-branch:
    description: 'Source branche to release'
    required: true

runs:
  using: "composite"
  steps:
    - name: Install Python
      uses: actions/setup-python@v4.2.0
      with:
        python-version: '3.10'
  
    - name: Print stuff
      run: echo "Hello World"
      shell: bash

    - name: Debug
      run: echo "${{ inputs.repository }}/${{ inputs.source-branch }}"
      shell: bash

    #- name: Install dependencies
    #  run: pip install -r requirements.txt
    #  shell: bash
